import type { Metadata } from "next";
import localFont from "next/font/local";

import BottomBar from "@/ui/bottom-bar";

import "./globals.css";

const pretendard = localFont({
  src: "./PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased justify-center flex`}
      >
        <div className="w-[440px] h-dvh bg-[#f8f9fa] relative">
          {children}
          <div className="absolute left-0 bottom-0">
            <BottomBar />
          </div>
        </div>
      </body>
    </html>
  );
}
